# Generated by Django 3.1.3 on 2021-05-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0003_auto_20210514_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('appellation', models.CharField(max_length=25)),
                ('record_status', models.CharField(choices=[('K', 'Kayıtlı'), ('NK', 'Kayıt Dondurulmuş'), ('B', 'Bıraktı'), ('D', 'Üniversite Dışı')], max_length=25)),
                ('uniqe_number', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('tel_no', models.CharField(max_length=11)),
                ('employee_no', models.CharField(max_length=11, unique=True)),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.library')),
            ],
        ),
    ]
