# Generated by Django 3.1.3 on 2021-05-28 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('appellation', models.CharField(max_length=25)),
                ('record_status', models.CharField(choices=[('K', 'Kayıtlı'), ('NK', 'Kayıt Dondurulmuş'), ('B', 'Bıraktı'), ('D', 'Üniversite Dışı')], max_length=25)),
                ('uniqe_number', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_no', models.CharField(blank=True, max_length=11, null=True)),
                ('employee_no', models.CharField(max_length=11, unique=True)),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
