# Generated by Django 3.2.3 on 2021-05-14 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('sources', '0003_auto_20210514_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emanet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('calculated_return_date', models.DateField()),
                ('days_to_return', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('price', models.FloatField(blank=True, null=True)),
                ('given_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.sources')),
                ('given_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
