# Generated by Django 3.1.3 on 2021-05-28 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_source_barcode', models.CharField(default='', max_length=11)),
                ('given_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, help_text='For creating loan,please set null', null=True)),
                ('calculated_return_date', models.DateField(editable=False)),
                ('days_to_return', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('price', models.FloatField(blank=True, null=True)),
                ('given_source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.sources')),
                ('given_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
