# Generated by Django 3.2.3 on 2021-05-15 13:25

import LoanService.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('LoanService', '0002_alter_emanet_calculated_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emanet',
            name='given_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', validators=[LoanService.models.maxbook_val]),
        ),
        migrations.AlterField(
            model_name='emanet',
            name='return_date',
            field=models.DateField(blank=True, help_text='For creating loan,please set null', null=True),
        ),
    ]
