# Generated by Django 3.2.3 on 2021-05-15 13:34

import LoanService.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanService', '0003_auto_20210515_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='emanet',
            name='given_source_barcode',
            field=models.CharField(default='232343243', max_length=11, validators=[LoanService.models.source_barcode_val]),
        ),
    ]
