# Generated by Django 3.2.3 on 2021-05-15 13:35

import LoanService.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanService', '0004_emanet_given_source_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emanet',
            name='given_source_barcode',
            field=models.CharField(default=' ', max_length=11, validators=[LoanService.models.source_barcode_val]),
        ),
    ]
