# Generated by Django 3.2.3 on 2021-05-16 14:31

import LoanService.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20210514_1612'),
        ('LoanService', '0006_alter_emanet_given_source_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emanet',
            name='given_source',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.sources'),
        ),
        migrations.AlterField(
            model_name='emanet',
            name='given_source_barcode',
            field=models.CharField(default='', max_length=11, unique=True, validators=[LoanService.models.source_barcode_val]),
        ),
    ]
