# Generated by Django 3.1.3 on 2021-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanService', '0010_auto_20210519_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emanet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
