# Generated by Django 3.1.3 on 2021-06-03 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_talep_drumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedd',
            name='request_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
