# Generated by Django 3.1.3 on 2021-05-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='lend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sources',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
