# Generated by Django 3.1.3 on 2021-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20210514_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='barcode',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
