# Generated by Django 3.1.3 on 2021-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_auto_20210514_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
